name: 'Auto Merge PRs'
description: 'Automatically merges pull requests'

inputs:
  owner:
    description: 'The owner of the repository'
    required: true
    type: 'string'
  repoName:
    description: 'The name of the repository'
    required: true
    type: 'string'
  prID:
    description: 'The ID of the pull request'
    required: true
    type: 'string'
  prTitle:
    description: 'The title of the pull request'
    required: true
    type: 'string'
  prBody:
    description: 'The body of the pull request'
    required: true
    type: 'string'
  GITHUB_TOKEN:
    description: 'The GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Auto Merge Pr's
      shell: bash
      run: |
        gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.owner }}/${{ inputs.repoName }}/pulls/${{ inputs.prID }}/merge \
          -F commit_title='${{ inputs.prTitle }}' \
          -F commit_message='${{ inputs.prBody }}'
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
