name: 'Create Pull Request'
description: 'Create a pull request using GitHub CLI'
inputs:
  token:
    description: 'GitHub token'
    required: true
  title:
    description: 'Title of the pull request'
    required: true
  body:
    description: 'Body of the pull request'
    required: true
  head:
    description: 'Head branch'
    required: true
  base:
    description: 'Base branch'
    required: true
  owner:
    description: 'Owner of the repository'
    required: true
  repo:
    description: 'Repository name'
    required: true
runs:
  steps:
    - name: Create Pull Request
      run: |
        echo "${{ inputs.token }}" > token.txt
        gh auth login --with-token < token.txt
        gh pr create \
          --title "${{ inputs.title }}" \
          --body "${{ inputs.body }}" \
          --head "${{ inputs.head }}" \
          --base "${{ inputs.base }}" \
          --repo "${{ inputs.owner }}/${{ inputs.repo }}"
      shell: bash
