name: 'Create Pull Request'
description: 'Create a pull request using GitHub CLI'
inputs:
  token:
    description: 'GitHub token'
    required: true
  title:
    description: 'Title of the pull request'
    required: true
  body:
    description: 'Body of the pull request'
    required: true
  head:
    description: 'Head branch'
    required: true
  base:
    description: 'Base branch'
    required: true
  owner:
    description: 'Owner of the repository'
    required: true
  repo:
    description: 'Repository name'
    required: true
  reviewers:
    description: 'Reviewers for the pull request, comma-separated'
    required: false
  assignees:
    description: 'Assignees for the pull request, comma-separated'
    required: false
  label:
    description: 'Labels for the pull request'
    required: false
  milestone:
    description: 'Milestone for the pull request'
    required: false
  draft:
    description: 'Whether the pull request is a draft'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      run: |
        echo "Logging in with token..."
        echo "${{ inputs.token }}" > token.txt
        gh auth login --with-token < token.txt
        DRAFT_OPTION=''
        if [ "${{ inputs.draft }}" = 'true' ]; then
          DRAFT_OPTION='--draft'
        fi
        echo "Processing labels..."
        LABELS="${{ inputs.label }}"
        IFS=',' read -ra LABEL_ARRAY <<< "$LABELS"
        for LABEL in "${LABEL_ARRAY[@]}"; do
          echo "Checking if label $LABEL exists..."
          EXISTS=$(gh api repos/${{ inputs.owner }}/${{ inputs.repo }}/labels/$LABEL --exit-status 2>&1 || echo 'not found')
          if [ "$EXISTS" = "not found" ]; then
            echo "Label $LABEL does not exist, creating it..."
            gh api -X POST repos/${{ inputs.owner }}/${{ inputs.repo }}/labels -f name=$LABEL -f color=ffffff
          fi
        done
        echo "Creating pull request..."
        gh pr create \
          --title "${{ inputs.title }}" \
          --body "${{ inputs.body }}" \
          --head "${{ inputs.head }}" \
          --base "${{ inputs.base }}" \
          --repo "${{ inputs.owner }}/${{ inputs.repo }}" \
          --reviewer "${{ inputs.reviewers }}" \
          --assignee "${{ inputs.assignees }}" \
          --label "$LABELS" \
          --milestone "${{ inputs.milestone }}" \
          $DRAFT_OPTION
      shell: bash
