name: Create Label
description: "Create PR Label"
inputs:
  token:
    required: true
    description: "Github token"
    default: ${{ github.token }}
  label:
    required: true
    description: "New label value"

runs:
  using: "composite"
  steps:
    
    - name: Create label
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/labels \
          -f name='${{ inputs.label }}'
